AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This template creates an AWS Config rule that checks for a strong IAM password policy.
  It also includes a remediation action that automatically enforces the policy.

Resources:
  IAMPasswordPolicyRule:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: iam-password-policy
      Source:
        Owner: AWS
        SourceIdentifier: IAM_PASSWORD_POLICY
      InputParameters: |
        {
          "RequireUppercaseCharacters": "true",
          "RequireLowercaseCharacters": "true",
          "RequireNumbers": "true",
          "RequireSymbols": "true",
          "MinimumPasswordLength": "14",
          "MaxPasswordAge": "90"
        }

  IAMPasswordPolicyRemediation:
    Type: AWS::Config::RemediationConfiguration
    Properties:
      ConfigRuleName: !Ref IAMPasswordPolicyRule
      TargetType: SSM_DOCUMENT
      TargetId: AWSConfigRemediation-SetIAMPasswordPolicy
      TargetVersion: '1'
      Parameters:
        AutomationAssumeRole:
          StaticValue:
            Values:
              - !GetAtt RemediationRole.Arn
        MinimumPasswordLength:
          StaticValue:
            Values:
              - '14'
        RequireUppercaseCharacters:
          StaticValue:
            Values:
              - 'true'
        RequireLowercaseCharacters:
          StaticValue:
            Values:
              - 'true'
        RequireNumbers:
          StaticValue:
            Values:
              - 'true'
        RequireSymbols:
          StaticValue:
            Values:
              - 'true'
        MaxPasswordAge:
          StaticValue:
            Values:
              - '90'
      Automatic: true
      MaximumAutomaticAttempts: 3
      RetryAttemptSeconds: 60

  RemediationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ssm.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonSSMAutomationRole
      Policies:
        - PolicyName: IAMPasswordPolicyRemediationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - iam:UpdateAccountPasswordPolicy
                Resource: '*'
